### ISSUE TITLE
create travis build + deploy

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-webgui#1]
- [x] travis.yml build script
- [x] deploy script

I guess deploy might be best, if we use webpack. Haven't checked yet. :-)

**Comment by allixender** [comment]
Travis build for first smart-webgui app AND webpack are in place and work, incl. testing.

deploy is currently semi-automated makefile docker build and k8s deploy scripts, not triggered by travis. same issue with the other projects. I am on it :+1:

**Comment by allixender** [comment]
admin app receives webhook and issues gke container builder with the prepared source package from the the travis build. the deployment is currently requiring manual activation (click in the web gui) through the admin app, but could also be automated . the process is now complete pipeline from github to travis to gce/gke
