### ISSUE TITLE
Graphs / Charts for SOS / WaterML2 time series visualisation

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-webgui#16]
- [x] Graphing implemented with Plotly
- [x] Backend provides JSON API for time series and capabilities access
- [x] Download via WML file

**Comment by grmpfhmbl** [comment]
Some chart components
http://sensor-widgets.readthedocs.io/en/latest/widgets.html
http://nvd3.org/examples/index.html
https://krispo.github.io/angular-nvd3/#/

**Comment by allixender** [comment]
This issue can be closed soon, review?

**Comment by allixender** [comment]
done
