### ISSUE TITLE
SEO sitemap exposure of our records, frontend part

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-webgui#18]
robots.txt with link to sitemap.xml

sitemap.xml static initial from categories links, dynamic generating from backend, so two sitemap links in robots txt, static sitemap.xml, and dynamic /api/v1/sitemap ...

Ideally every entry in our own catalogue should be found via google. So we basically need URLs like ".../entry/" that opens a detail view with backlinks. We have to discuss that in detail.

 BUT no FRAGMENTS (but we use /#/ Hash nav?!?!)

https://www.yearofmoo.com/2012/11/angularjs-and-seo.html

**Comment by grmpfhmbl** [comment]
Every entry in our own catalogue should be found via google. So we basically need URLs like ".../entry/<UUID>" that opens a detail view with backlinks. We have to discuss that in detail.

**Comment by allixender** [comment]
sitemap.xml initial from categories links
