### ISSUE TITLE
Initial Metadata entry form

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-webgui#21]
see for base template from old smart portal:
- https://github.com/ZGIS/smart-portal-webgui/blob/master/src/app/workbench/metadata-editor.component.ts
- https://github.com/ZGIS/smart-portal-webgui/blob/master/src/app/workbench/metadata-editor.component.html

The thing preferably as a wizard type thing or something, at least with some tabs so it is not too overwhelming, like in the old version:

http://portal.smart-project.info/smart/meta/add

related backend task:
- https://github.com/ZGIS/smart-portal-backend/issues/4

**Comment by grmpfhmbl** [comment]
done
