### ISSUE TITLE
Minor GUI issues + improvements

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-webgui#39]
- [x] delete true / false from checkboxes sac category /#/workbench/add-data
- [x] open accordeon by default in /#/workbench/my-data
- ~~have UPLOAD DONE message in /#/workbench/upload-file~~ is now https://github.com/ZGIS/smart-portal-webgui/issues/53
- [x] move back/next button to footer line in http://localhost:8080/#/workbench/add-data

Other questions as user questions in Trello!

**Comment by allixender** [comment]
can be closed? Further complex issues have been create separately: 

- https://github.com/ZGIS/smart-portal-webgui/issues/53
- https://github.com/ZGIS/smart-portal-webgui/issues/46
