### ISSUE TITLE
Prevent overwhelming amount of notifications

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-webgui#48]
For example in advanced search component, the "found more than 100 features, for more click show all" 

possible variations:

- [ ] close most messages after 3 -5 seconds
- [ ] with many identical active messages, only show one time and just mention $4x", "5x" ..
- [ ] keep messages in fixed diff and add scroll bar to not pollute user interface (because currently they are sitting  above gui

**Comment by allixender** [comment]
is duplicate of https://github.com/ZGIS/smart-portal-webgui/issues/54

**Comment by grmpfhmbl** [comment]
Message can have IDs now. Only the last message with a given ID is shown. Think of ID more like a category of the message.
Messages will be dismissed after 5000ms automatically by default. Can be turned off by setting delay to -1 (see addErrorNotification) or set to a different value for any given message.
