### ISSUE TITLE
Make template URLs relative

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-webgui#5]
see https://github.com/angular/angular/issues/6053
see http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/
see https://github.com/systemjs/systemjs/issues/1030
see http://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html

**Comment by allixender** [comment]
with "base" tag in index.html should be ok? Also, no systemjs anymore :smile:

**Comment by allixender** [comment]
@grmpfhmbl Can be closed?

**Comment by grmpfhmbl** [comment]
Yes, seems to be solved.
