### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-webgui#54]
Notifications, to decide, make configurable or convention?

- [x] many errors (and search 100+ results) can fade out after couple seconds

- [x] some errors could be stackable (2x ..5x, so they don't flood screen, e.g. keep in one box with scroll bar

- [ ] inserted as UUID seems so far interesting info, might be displayed differently, or is the  one type that stays on until clicked away (most users won't need to remember the UUID as they will hopefully find it in their collections, possibly should add the info, which field in the OwcEntry this UUD is used, technically could even use the EntryId which is generated in the backend)

- [x] Login Token Error should not be displayed and handled silently, because it will always show when not logged in (not good) !!!

**Comment by grmpfhmbl** [comment]
Message can have IDs now. Only the last message with a given ID is shown. Think of ID more like a category of the message.
Messages will be dismissed after 5000ms automatically by default. Can be turned off by setting delay to -1 (see addErrorNotification) or set to a different value for any given message.
