### ISSUE TITLE
Look for / create typings for OL3

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-webgui#7]
As far as I see, there are no typings for OL3. Would be nice to have some. There's already an issue about that here https://github.com/openlayers/ol3/issues/3147

Also see here https://github.com/typings/typings
and here https://github.com/typings/registry

**Comment by allixender** [comment]
Also new @types npm packing of typings:

https://www.npmjs.com/package/@types/openlayers

**Comment by allixender** [comment]
https://www.npmjs.com/package/angular2-openlayers ?
